FROM node:20.9.0-alpine as build

WORKDIR /usr/src/app

RUN npm install -g npm@10.2.4

COPY . .

RUN npm install

EXPOSE 5173

RUN npm run build

FROM nginx:alpine

COPY --from=build /usr/src/app/dist 

RUN rm /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]